# docker-compose.yml
version: "3.0"
services:
  frontapp:
    build: ./FrontEnd
    image: qkrdnjs0323/frontapp:latest
    ports:
      - "8081:8080"

  backapp:
    build: ./BackEnd
    image: qkrdnjs0323/backapp:latest
    depends_on:
      - frontapp
