# docker-compose.yml
services:
  frontapp:
    build: ./FrontEnd
    image: ${DOCKER_USR}/frontapp:${BUILD_NUMBER}
    ports:
      - "8081:80"
    depends_on:
      - backapp

  backapp:
    build: ./BackEnd
    image: ${DOCKER_USR}/backapp:${BUILD_NUMBER}
    ports:
      - "5000:5000"

