# docker-compose.yml

services:
  frontapp:
    build: ./FrontEnd
    image: qkrdnjs0323/frontapp:latest
    ports:
      - "8080:80"

  backapp:
    build: ./BackEnd
    image: qkrdnjs0323/backapp:latest
    ports:
      - "5000:5000"
    depends_on:
      - frontapp
